name = "fedora-iot-infra"
description = "Fedora IoT with GPS HAT (u-blox M8 + RV-3028-C7 RTC) support"
version = "1.0.0"
modules = []
groups = []

# Base packages for GPS/RTC functionality
[[packages]]
name = "pps-tools"
version = "*"

[[packages]]
name = "minicom"
version = "*"

[[packages]]
name = "gpsd"
version = "*"

[[packages]]
name = "gpsd-clients"
version = "*"

[[packages]]
name = "chrony"
version = "*"

[[packages]]
name = "i2c-tools"
version = "*"

# Kernel modules configuration
[[customizations.kernel]]
append = "i2c_arm=on console=tty0 console=ttyS0,115200"

# Services configuration
[[customizations.services]]
enabled = ["gpsd", "chronyd", "gps-init.service", "hwclock-sync.service"]
disabled = ["fake-hwclock"]

# User configuration
[[customizations.user]]
name = "core"
description = "Core user with GPS hardware access"
groups = ["wheel", "dialout", "i2c", "tty"]

# File customizations
[[customizations.files]]
path = "/etc/modules-load.d/gps-rtc.conf"
data = """
# I2C modules
i2c-dev
i2c-bcm2835

# RTC module
rtc-rv3028

# PPS module
pps-gpio
"""

[[customizations.files]]
path = "/boot/firmware/config.txt.d/10-gps-rtc.conf"
data = """
# Enable I2C
dtparam=i2c_arm=on

# RTC Configuration - RV-3028-C7 at address 0x52
dtoverlay=i2c-rtc,rv3028,addr=0x52
dtparam=rtc=off

# PPS Configuration for GPS
dtoverlay=pps-gpio

# Serial configuration for GPS
enable_uart=1
dtparam=uart=on
"""

[[customizations.files]]
path = "/etc/systemd/system/hwclock-sync.service"
data = """
[Unit]
Description=Sync system time with hardware clock
After=systemd-modules-load.service
Before=time-set.target
Wants=time-set.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/hwclock --hctosys
ExecStop=/usr/sbin/hwclock --systohc
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""

[[customizations.files]]
path = "/etc/systemd/system/gps-init.service"
data = """
[Unit]
Description=GPS HAT Initialization
After=systemd-modules-load.service
Before=gpsd.service

[Service]
Type=oneshot
ExecStart=/bin/stty -F /dev/ttyS0 115200 cs8 -cstopb -parenb
ExecStart=/bin/bash -c 'until [ -c /dev/pps0 ]; do sleep 1; done'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""

[[customizations.files]]
path = "/etc/udev/rules.d/99-gps-rtc.rules"
data = """
# GPS HAT RTC device
KERNEL=="rtc0", SUBSYSTEM=="rtc", ATTRS{name}=="rv3028", SYMLINK+="rtc-gps"

# GPS serial device
KERNEL=="ttyS0", SUBSYSTEM=="tty", SYMLINK+="gps0", MODE="0666"

# PPS device
KERNEL=="pps0", SUBSYSTEM=="pps", SYMLINK+="pps-gps", MODE="0666"
"""

[[customizations.files]]
path = "/etc/gpsd/gpsd.conf"
data = """
# Configuration for gpsd
DEVICES="/dev/ttyS0"
GPSD_OPTIONS="-n -G"
USBAUTO="false"
"""

[[customizations.files]]
path = "/lib/udev/hwclock-set"
mode = "0755"
data = """
#!/bin/sh
# Customized hwclock-set for RTC hardware support
# Commented out systemd check to allow hardware RTC
# if [ -e /run/systemd/system ] ; then
#     exit 0
# fi

# Commented out to allow hardware RTC to work properly
# /sbin/hwclock --rtc=$dev --systz
"""

[[customizations.files]]
path = "/etc/chrony.conf"
data = """
# Chrony configuration for GPS/RTC synchronization
pool 2.fedora.pool.ntp.org iburst

# GPS/PPS reference clocks
refclock SHM 0 refid GPS precision 1e-1 offset 0.0 delay 0.2
refclock PPS /dev/pps0 refid PPS precision 1e-6

# RTC as fallback
rtcsync

# Other standard chrony settings
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtconutc
"""